### PR TITLE
ATV-205 | Fix document status change causing error with json payload

### PR DESCRIPTION
**Pull request by charn**
This PR fixes 500 error when trying to change document status using a json formatted payload.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**ATV-API branch is deployed to platta: https://atv-api-hki-kanslia-atv-dev.apps.arodevtest.hel.fi** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ATV-API branch is deployed to platta: https://atv-api-hki-kanslia-atv-dev.apps.arodevtest.hel.fi** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ATV-API branch is deployed to platta: https://atv-api-hki-kanslia-atv-dev.apps.arodevtest.hel.fi** :rocket::rocket::rocket:

**Review by danipran — APPROVED** [review]
LGTM :+1:

**Comment by terovirtanen** [comment]
**ATV-API branch is deployed to platta: https://atv-api-hki-kanslia-atv-dev.apps.arodevtest.hel.fi** :rocket::rocket::rocket:

**Pull request merged**
